# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20181116_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
